version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: airlines
      MYSQL_ROOT_PASSWORD: weLcOme2.
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-buffer-pool-size=1G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
      - --default_storage_engine=InnoDB      
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=weLcOme2.--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 3
  finartz-airlines-app:
    restart: on-failure
    build: ./
    expose:      
      - "10222"
    ports:
      - 10222:10222
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
