version: '3'
services:
  docker-mysql:
    network_mode: host
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: airlines
      MYSQL_ROOT_PASSWORD: weLcOme2.
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
  finartz-airlines-app:
    restart: on-failure
    build: ./
    expose:      
      - "8080"
    ports:
      - 8080:8080  
    network_mode: host     
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql            