version: '3'
services:
  docker-mysql:
    network_mode: host
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: airlines
      MYSQL_ROOT_PASSWORD: weLcOme2.
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-buffer-pool-size=1G
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
      - --default_storage_engine=InnoDB      
    ports:
      - "3306:3306"
  finartz-airlines-app-v1:
    restart: on-failure
    build: ./
    expose:      
      - "8080"
    ports:
      - 8080:8080  
    network_mode: host     
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql            